### ISSUE TITLE
CPLEX academic version "Page Not Found"

### ISSUE THREAD

**Issue by mebbert** [YosefLab/Compass#102]
Hello,

Anyone been able to access the full academic version of CPLEX recently? As noted in other posted issues, COMPASS requires the full version of CPLEX, which is free for academic users. IBM's website has changed from what the COMPASS installation page describes. I have tried several routes to find the free version for academic users, but I keep getting a "Page Not Found" error on IBM's website.

To replicate (as of today):
1. Go to IBM.com
2. Search for "cplex"
3. Click on "CPLEX Optimization Studio is free for students and academics!"
4. Observe the "Page Not Found" error.

Other browsing attempts had the same ending.

Anyone have a suggestion? I'll also try to submit an issue through IBM's website, but not super hopeful that will be effective.

**Comment by deto** [comment]
What if you sign in through here?  (No longer an academic so I can't make
an account)

https://www.ibm.com/academic/home

**Comment by mebbert** [comment]
Thanks for the suggestion. I tried that, just in case, but no dice. It seems to simply be a broken link rather than any sort of authentication type (i.e., academic vs. commercial).

There's another page that explicitly states to go to the page I mentioned, and the link is dead from there, too. Not sure if it's accessible without logging in, but it's a general info page: https://www.ibm.com/support/pages/how-do-i-download-cplex-optimization-studio?mhsrc=ibmsearch_a&mhq=CPLEX

The dead page seems to be part of the IBM TechXchange Community, so I've sent an email to support@communitysite.ibm.com. Hopefully someone's home.

Will try to respond here if I learn anything new.

**Comment by mebbert** [comment]
FYI, IBM fixed the website and I was able to download.
