### ISSUE TITLE
question about normalization that can be used with this tool 

### ISSUE THREAD

**Issue by lwhitmore** [YosefLab/Compass#20]
Hi!  I have more of a question than an issue but I am wondering if I could use the the scaled data calculated by seurat for this analysis instead of the TPM data.   I am using 10x data. 
Thanks for any help you can provide!
Leanne

**Comment by chu96** [comment]
I have the same concern.

**Comment by jiaqiqi77** [comment]
HI ! I tried to use scaled data but failed ,But when I input an expression matrix changing  one TPM to a negative numeric ,it works ,so I think the reason why scales matrix did not work is not the negitive value ,look forward to your guide! thanks

**Comment by allonw** [comment]
Hi,

When using Seurat, Compass expects the input generated by the `NormalizeData` (which scales for library size), and not `ScaleData` (which z-scales the data). 

Please also note that Compass also expects linear-scale input, whereas  and not log-transformed which is currently the default of Seurat's `NormalizeData`, so this argument needs to be set. For example, in Seurat's PBMC tutorial, change the `NormalizeData` command to:
`pbmc <- NormalizeData(pbmc, normalization.method = "RC", scale.factor = 10000)`

and then export `pbmc@assays$RNA@data` to be Compass's output.

And yes, for 10x data the input should linear-scale CPM and not linear-scale TPM as in full-transcript sequencing protocols.

**Comment by DPLemonade** [comment]
Marking as resolved.
