### ISSUE TITLE
incomplete compass run

### ISSUE THREAD

**Issue by lwhitmore** [YosefLab/Compass#22]
When I ran compass it didn't output any errors but did not generate the cell_metadata.csv (which may have to be generated independently?) or the linear_gene_expression_matrix.tsv.  Would anyone know why this is? 

Thanks for your help!
Leanne

**Comment by schel337** [comment]
Hi, sorry for the very late response. We've only recently started checking this page again.

Compass should output a reactions.tsv with scores per reaction and per sample and it would take in a gene expression matrix. I believe for cell metadata you would have to use something other than Compass.

**Comment by DPLemonade** [comment]
Marking as resolved due to inactivity.
