### ISSUE TITLE
mtx documentation

### ISSUE THREAD

**Issue by allonw** [YosefLab/Compass#27]
Discrepancy in the mtx input documentation:
2 arguments (https://yoseflab.github.io/Compass/user-guide.html) 
or 3 arguments (https://yoseflab.github.io/Compass/tutorial.html)

Will having a --mtx-data arg that is mutually exclusive with --data make the cmd line args easier to parse?

**Comment by schel337** [comment]
First issue has been clarified in documentation for now. The third argument is optional.

Sure, I've switched over to that now.
