### ISSUE TITLE
Adding requirements

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#29]
I did not find a requirements file (except for Cplex). Could you add this so that the installation can run more smoothly? E.g. mine errored out as I did not have numpy in my environment.

**Comment by schel337** [comment]
Hi, sorry about the slow response time. We have not checked the issues page in a while, but we've now remembered its existence.

There is a list of requirements in setup.py that should be automatically installed with pip or by running setup.py. Did you install with "pip install git+https://github.com/yoseflab/Compass.git" or by cloning the repo and running setup.py? Either of those should automatically install the required packages except for Cplex.

**Comment by Hrovatin** [comment]
I did the pip install. I see numpy is in the  requirements. Odd.

**Comment by Hrovatin** [comment]
Actually, the problem could be that your setup.py requires numpy in imports already?

**Comment by schel337** [comment]
That seems very possible. This code was written by an earlier contributor and I haven't had a reason to look too closely at it in the past. I'll test out the installation on a completely fresh python setup and see what needs to be fixed.

**Comment by schel337** [comment]
I've ended up adding the NumPy installation to the documentation, as I was not satisfied with either of the workarounds I tested.
