### ISSUE TITLE
Latent data and micropooling & micropooling large memory requirement

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#31]
I wanted to use microppoling with custom latent data. However, it seems that latent data is not used in micropooling and that microppoling does not create new corrected latent data. Can you let me know how can I use both params or if I just misunderstood the code?

I have tried to modify the code to use latent data in microclustering and to then average the latent data as well. But I can not seem to run it due to lack of memory. - I am running Compass with 350G RAM and ~100k cells, but the job dies during micro clustering. This seems a bit odd to me since I can do leiden on this data with much less memory.

I have changed this part of the code, but not yet sure if it works as my jobs keep dying due to out of memory issues. https://github.com/Hrovatin/Compass/blob/599c4e70959be124c46fa3c0bb6847f0e9ef6b1e/compass/main.py#L355

**Comment by schel337** [comment]
Latent data was not integrated into the micropooling earlier, but now it pools based on clustering in the latent space. You can use both parameters together and the latent space will be used for the clustering.

We're currently working on the memory usage issues and have been able to replicate unusually high memory usage on some datasets. We'll push a fix as soon as possible.

**Comment by schel337** [comment]
The memory issues with micropooling should be fixed now. In particular, no more dense sample by sample arrays are being used.
