### ISSUE TITLE
Is it possible to restart Compass computation?

### ISSUE THREAD

**Issue by Hrovatin** [YosefLab/Compass#34]
My Compass run stopped due to time limit on server at ~70% of computed results. Is it possible to restart the job and use the already computed results/compute what is still missing?

In the documentation it says that it should be possible (https://yoseflab.github.io/Compass/tutorial.html?highlight=restart), but I could not find any instructions on how to do it.

**Comment by schel337** [comment]
All you have to do is rerun the previous compass command, and so long as the temporary directory is still present (_tmp by default), Compass will retrieve all of the results there.

**Comment by Hrovatin** [comment]
Thank you!
