### ISSUE TITLE
How to interpret the COMPASS result?

### ISSUE THREAD

**Issue by zhanglab2008** [YosefLab/Compass#37]
I ran COMPASS with success in my dataset. However, I was confused by the output. For example, if a metabolic pathway have same number of downregulated and upregulated reactions (based on Cohen's d) in a comparison (let's say, disease versus healthy), does it mean that this metabolic pathway has no change?
I wonder how you quantify the reactions and give an answer to a simple question: whether the metabolism is up or down in disease?
Any input will be much appreciated!!!

**Comment by allonw** [comment]
Sorry for the late response!

One of the points we make in the manuscript is that sometimes an entire metabolic pathway is upregulated in condition A compared to condition B, but very often this is not the case (compare for example figure 2c to 2e [here](https://www.biorxiv.org/content/10.1101/2020.01.23.912717v1.full)). 

If you see both upregulated and downregulated reactions in a pathway, and the effect sizes and statistical significance are large enough, then the conclusion would be there is a metabolic effect, but the pathway doesn't behave coherently in your data. For example, only part of arginine metabolism cycle can be upregulated in condition A but not arginine metabolism as a whole (for example, see figure 1d [here](https://www.biorxiv.org/content/10.1101/2020.01.23.911966v1.full) and compare it to the canonical arginine metabolism pathway as in [KEGG](https://www.genome.jp/kegg-bin/show_pathway?mmu00330) for example). If the effect sizes are small and insignificant, then it's sensible to conclude that the pathway doesn't change between the two conditions.

So, to interpret the results, you can look for smaller subsets of reactions with significant and consistent in their direction (up/down) changes, and compare them to pathway compendia as KEGG. We're now looking at ways to semi-automate this process.

Hope this helps, and please don't hesitate to bring up any other or followup questions.

**Comment by zhanglab2008** [comment]
That makes sense! and thanks so much for the comments!

**Comment by allonw** [comment]
gladly, and don't think twice to ask if there's anything else we can help with!
