### ISSUE TITLE
TypeError("cannot pickle 'SwigPyObject' object

### ISSUE THREAD

**Issue by raman91** [YosefLab/Compass#46]
Hi, 

I am running compass with own model but on running i get an error:

'<multiprocessing.pool.ExceptionWithTraceback object at 0x7fac7a605e80>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'. 

Do you know how to solve this ?? 

Thanks

**Comment by raman91** [comment]
Hi @schel337, thanks for the reply. We can share our model with you. Please let us know the email to send to? Thanks

**Comment by schel337** [comment]
You can send it to me at schel337@berkeley.edu

**Comment by deto** [comment]
From experience, this typically happens when some other sort of exception
is being thrown from within the subprocess.  The exception handler for this
original exception then tries to pickle some objects to report back, and
from here the second error happens.  I believe in the past I've been able
to diagnose by running things in a single-threaded manner to see what the
underlying cause is.

**Comment by raman91** [comment]
Thank you. We had shared the model with you.

**Comment by schel337** [comment]
Resolved this over email a while ago, but for posterity's sake this was because Compass assumed models would be compatible with 0 flux through any given reaction. This has now been corrected to allow for models where reactions always ahve nonzero flux.

**Comment by FADHLyemen** [comment]
!compass --data expression.tsv --num-processes 2 --species homo_sapiens
give me the same error
I used your test data
https://github.com/YosefLab/Compass/blob/master/compass/Resources/Test-Data/tsv_format/expression.tsv

**Comment by FADHLyemen** [comment]
Successfully installed compass-sc-0.9.10.2
to install cplex I did `conda install -c ibmdecisionoptimization cplex`

**Comment by sonusubudhi** [comment]
> !compass --data expression.tsv --num-processes 2 --species homo_sapiens give me the same error I used your test data https://github.com/YosefLab/Compass/blob/master/compass/Resources/Test-Data/tsv_format/expression.tsv

Hi, I am also having the same issue while implementing the test dataset provided in the compass package.

**Comment by oyxf** [comment]
How could  i resolve this error? I encounter the same  issue when i am  runing cmd as  follow： 
compass --data expression.tsv --num-processes 10 --species homo_sapiens

**Comment by massonix** [comment]
I found the same error

**Comment by sid5427** [comment]
good day - I am getting the same error while trying to run the example from COMPASS's documentation.

here is the end of the log generated by our cluster - 

 ```
0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1013 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1013 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]
  0%|      	| 0/1022 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/users/user_name/.conda/envs/py_3_8/bin/compass", line 8, in <module>
	sys.exit(entry())
  File "/users/user_name/.conda/envs/py_3_8/lib/python3.8/site-packages/compass/main.py", line 572, in entry
	precacheCompass(args=args)
  File "/users/user_name/.conda/envs/py_3_8/lib/python3.8/site-packages/compass/main.py", line 873, in precacheCompass
	for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "/users/user_name/.conda/envs/py_3_8/lib/python3.8/multiprocessing/pool.py", line 868, in next
	raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x2ae336f7b700>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'

```

**Comment by deto** [comment]
The issue is the error reporting when using multiprocessing and this hides the real exception.  Try running it with one core instead to see what the real error is. Most likely, you have the community edition of CPLEX which can't handle the model sizes.  Instead, get the academic edition which is more fully featured.

**Comment by skoturan** [comment]
Hi, I have just come across the same error pointing to installing the free academic version of cplex vs docplex. 

`...multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x14f4c1bd99a0>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'`


Can you please provide the link where I can download this from? I can't find this on the redirected link (quoted below) from your tutorial documentation.

> The issue is the error reporting when using multiprocessing and this hides the real exception. Try running it with one core instead to see what the real error is. Most likely, you have the community edition of CPLEX which can't handle the model sizes. Instead, get the academic edition which is more fully featured. See "Installing CPLEX" instructions [here](https://yoseflab.github.io/Compass/install.html#id3)

Thanks!
