### ISSUE TITLE
Can we use “extdata/RECON2/reaction_metadata.csv” for mice's compass analysis？

### ISSUE THREAD

**Issue by 1213812138zqc** [YosefLab/Compass#54]
Currently, we are analyzing our scRNA-seq data obtained from the mice through Compass platform. I want to ask if we can use “extdata/RECON2/reaction_metadata.csv”(suitable for human in your analysis) to perform downstream analysis.

**Comment by schel337** [comment]
Yes, in our analysis the Th17 cells actually come from mice and we used that metadata for analysis of the cells. The use of Recon2 is a limitation of the study, among those we list in the Cell paper, though we have been looking into adding other models to Compass. I will add some clarifications to our online documentation.

The species parameter on the command line determines whether to look for human or mouse genes, if that helps clarify things. It does not change the model.

**Comment by 1213812138zqc** [comment]
Thanks for detailed explanations

**Comment by allonw** [comment]
Thanks Brandon for the answer. I'll just add that it's common in FBA studies to use Recon also for mouse data because of its magnitude and breadth and despite the differences that exist between murine and human metabolism.
