### ISSUE TITLE
Error running compass

### ISSUE THREAD

**Issue by darwinchangz** [YosefLab/Compass#56]
Hello, I am having an issue running compass. I believe that the version was recently updated, because it had been working before. compass -h works so I know it's not an issue with cplex, but rather one of the python packages named anndata? Perhaps there is a version requirement? I am on python 3.6.8.
Error is below:

Traceback (most recent call last):
  File "/home/80022926/.local/bin/compass", line 11, in <module>
    load_entry_point('compass-sc==0.9.9.9', 'console_scripts', 'compass')()
  File "/home/80022926/.local/lib/python3.6/site-packages/compass/main.py", line 416, in entry
    diffs = [x for x in args.keys() if args[x] != temp_args[x] and x not in ignored_diffs]
  File "/home/80022926/.local/lib/python3.6/site-packages/compass/main.py", line 416, in <listcomp>
    diffs = [x for x in args.keys() if args[x] != temp_args[x] and x not in ignored_diffs]
KeyError: 'anndata_output'

Any assistance would be appreciated!

**Comment by schel337** [comment]
That's a bug I introduced by not accounting for previous runs of Compass that won't have those settings in the _temp_args.json in the temporary directory Compass makes (probably _tmp/). If you remove that file it should work, though it won't give warnings if any settings are different than the one that was already run. I'll also push a fix.

**Comment by darwinchangz** [comment]
thank you! removing the json solved the issue.
