### ISSUE TITLE
CPLEX - data size issue

### ISSUE THREAD

**Issue by sid5427** [YosefLab/Compass#80]
Good day,

We are trying to run compass on a dataset of our choice. However I am getting the pickle SwigPyObject error as reported by others while running tool with multiple processes.

`multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x2b70445cab00>'. Reason: 'TypeError("can't pickle SwigPyObject objects")'`

and when I run the tool with a single process I get an error related to limitations of problem size limit due to using the community edition - 

`cplex.exceptions.errors.CplexSolverError: CPLEX Error  1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.`

Would installing the academic version help? any advice with on this issue?

Thanks- 

Sidharth Sen

**Comment by deto** [comment]
Yes - you need either the paid commercial edition or the fully-featured academic edition to handle the model size.
