### ISSUE TITLE
No module named 'compass_analysis'

### ISSUE THREAD

**Issue by muralyv** [YosefLab/Compass#83]
Following compass Analysis in https://yoseflab.github.io/Compass/notebooks/Demo.html

In the cell 3
'from compass_analysis import cohens_d, wilcoxon_test, get_reaction_consistencies, get_metareactions, labeled_reactions, amino_acid_metab' step,  error showing 

ModuleNotFoundError: No module named 'compass_analysis'

**Comment by DPLemonade** [comment]
Marking as resolved. To run the postprocessing notebook, you should make sure that `compass_analysis.py` is located in the same directory.
