### ISSUE TITLE
Can the interrupted Compass code continue to run?

### ISSUE THREAD

**Issue by qiuju-Zhang** [YosefLab/Compass#85]
I have run part of the cells in the dataset using Compass, but the code was interrupted due to server disk space. So I would like to ask if there is a way to continue running from where the code was interrupted last time？
Thanks!!

**Comment by goterm** [comment]
yes, see https://github.com/YosefLab/Compass/issues/34

**Comment by DPLemonade** [comment]
Marking as resolved. To reiterate, as long as the temporary directory is present then COMPASS will continue from where it left off.
