### ISSUE TITLE
Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'

### ISSUE THREAD

**Issue by hello257** [YosefLab/Compass#91]
My code is as below:
compass --data expression.tsv --num-processes 20 --species homo_sapiens
Building up model cache
  0%|                                                                                                                                                               | 0/511 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "xxxxx", line 8, in <module>
    sys.exit(entry())
  File "xxxxx", line 572, in entry
    precacheCompass(args=args)
  File "xxxxx", line 873, in precacheCompass
    for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "xxxxx", line 870, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f8f56110790>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'

Any reply would be appreciated!

**Comment by YuanJIE-H** [comment]
Have you solved this problem? I had the same problem and couldn't solve it

**Comment by hello257** [comment]
Sorry, I have not solved this problem yet.

发件人: YuanJIE-H
发送时间: 2023年2月15日 16:24
收件人: YosefLab/Compass
抄送: hello257; Author
主题: Re: [YosefLab/Compass] Reason: 'TypeError("cannot pickle'SwigPyObject' object")' (Issue #91)

Have you solved this problem? I had the same problem and couldn't solve it

**Comment by mikecuoco** [comment]
I'm having the same problem

**Comment by brycemash** [comment]
I'm also having a similar problem: 
/(base) -bash:uger-c012:/ 634 $ compass --precache --species homo_sapiens
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
Traceback (most recent call last):
  File "/home/unix/mashimo/.local/bin/compass", line 8, in <module>
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:12<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:14<?, ?it/s]
  0%|                                                                                                             | 0/197 [00:13<?, ?it/s]
    sys.exit(entry())
  File "/home/unix/mashimo/.local/lib/python3.9/site-packages/compass/main.py", line 572, in entry
    precacheCompass(args=args)
  File "/home/unix/mashimo/.local/lib/python3.9/site-packages/compass/main.py", line 873, in precacheCompass
    for sub_cache in pool.imap_unordered(partial_map_fun, reaction_chunks):
  File "/broad/software/free/Linux/redhat_7_x86_64/pkgs/python_3.9.2/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x2b236c25cf70>'. Reason: 'TypeError("cannot pickle 'SwigPyObject' object")'

**Comment by KunFang93** [comment]
> the academic version

Could you please shed some lights how to download the academic version of it... Thanks!

**Comment by KunFang93** [comment]
> > the academic version
> 
> Could you please shed some lights how to download the academic version of it... Thanks!



> this problem also confuses me a lot.
> 
> For the solution: The community version of cplex is not enough, the academic version is correct. Download the correct version of cplex studio.

Could you please shed some lights how to download the academic version of it... Thanks!
